### Updates an existing patient entity
PUT http://localhost:4000/patients/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "name": "Freddy Krueger",
  "email": "freddy.krueger@elmstreetnightmares.com",
  "address": "1428 Elm Street, Springwood, Ohio",
  "dateOfBirth": "1942-09-13"
}

###